
dailykos = read.csv("dailykos.csv", header=FALSE)
str(dailykos)
distances = dist(dailykos[2:3431], method = "euclidean")
dailykosMatrix = as.matrix(dailykos)
str(dailykosMatrix)

dailykosVector = as.vector(dailykosMatrix)
str(dailykosVector)
distance = dist(dailykosVector, method = "euclidean")

dailykos = read.csv("dailykos.csv")
kosdist = dist(dailykos, method = "euclidean")
kosHierClust = hclust(kosDist, method="ward.D")
plot(kosHierClust)
kosClusters = cutree(kosHierClust, k = 7)
cluster1 = subset(dailykos, kosClusters==1)
cluster1
summary(cluster1)
cluster2 = subset(dailykos, kosClusters==2)
str(cluster2)
cluster3 = subset(dailykos, kosClusters==3)
str(cluster3)
cluster4 = subset(dailykos, kosClusters==4)
str(cluster4)
cluster5 = subset(dailykos, kosClusters==5)
str(cluster5)
cluster6 = subset(dailykos, kosClusters==6)
str(cluster6)
cluster7 = subset(dailykos, kosClusters==7)
str(cluster7)

tail(sort(colMeans(cluster1)))
tail(sort(colMeans(cluster2)))
tail(sort(colMeans(cluster3)))
tail(sort(colMeans(cluster4)))
tail(sort(colMeans(cluster5)))
tail(sort(colMeans(cluster6)))
tail(sort(colMeans(cluster7)))


library(caTools)
set.seed(1000)
KMC = kmeans(dailykos, centers = 7)
str(KMC)
dailyClusters = KMC$cluster
KMC$centers[2]
KMC$centers[1]
KMC$centers[3]
KMCcluster1 = subset(dailykos, dailyClusters==1)
str(KMCcluster1)
KMCcluster2 = subset(dailykos, dailyClusters==2)
str(KMCcluster2)
KMCcluster3 = subset(dailykos, dailyClusters==3)
str(KMCcluster3)
KMCcluster4 = subset(dailykos, dailyClusters==4)
str(KMCcluster4)
KMCcluster5 = subset(dailykos, dailyClusters==5)
str(KMCcluster5)
KMCcluster6 = subset(dailykos, dailyClusters==6)
str(KMCcluster6)
KMCcluster7 = subset(dailykos, dailyClusters==7)
str(KMCcluster7)

tail(sort(colMeans(KMCcluster1)))
tail(sort(colMeans(KMCcluster2)))
tail(sort(colMeans(KMCcluster3)))
tail(sort(colMeans(KMCcluster4)))
tail(sort(colMeans(KMCcluster5)))
tail(sort(colMeans(KMCcluster6)))
tail(sort(colMeans(KMCcluster7)))
table(cluster2, KMCcluster1)
table(kosClusters, KMC$Cluster)
table(kosHierClust, KMC$Cluster)
table(kosHierClust, dailyCluster)
table(kosClusters, dailyCluster)
table(kosClusters, dailycluster)
table(kosClusters, dailyClusters)