
climate = read.csv("climate_change.csv")
str(climate)
climate_Training = subset(climate, Year <= 2006)
str(climate_Training)
climate_Test = subset(climate, Year > 2006)
str(climate_Test)
TempReg = lm(Temp ~ MEI + CO2 + CH4 + N2O + CFC.11 + CFC.12 + TSI + Aerosols, data = climate_Test)
summary(TempReg)
TempReg = lm(Temp ~ MEI + CO2 + CH4 + N2O + CFC.11 + CFC.12 + TSI + Aerosols, data = climate_Training)
summary(TempReg)
cor(climate_Training)
N20Reg = lm(N2O ~ MEI + N2O + TSI + Aerosols, data = climate_Training)
N20Reg = lm(N2O ~ MEI + TSI + Aerosols, data = climate_Training)
summary(N2O)
summary(N2OReg)
stepclimate = step(TempReg)
summary(stepclimate)
predictTest = predict(stepclimate, newdata=climate_Test)
predictTest
SSE = sum((climate_Test$Temp - predictTest)^2)
SST = sum((climate_Test$Temp - mean(climate_Training$Temp))^2)
# 1 - SSE / SST
TempReg2 = lm(N2O ~ MEI + N2O + TSI + Aerosols, data = climate_Training)
TempReg2 = lm(Temp ~ MEI + N2O + TSI + Aerosols, data = climate_Training)
summary(TempReg2)