DateConvert = as.Date(strptime(mvtWeek$Date, "%m/%d/%y %H:%M"))
mvt$Month = months(DateConvert)
mvtWeek$Month = months(DateConvert)
mvtWeek$Weekday = weekdays(DateConvert)
str(mvtWeek)
tapply(IBM$Arrest, mvtWeek$Month, max)
tapply(mvtWeek$Arrest, mvtWeek$Month, max)
tapply(mvtWeek$Month, mvtWeek$Arrest, max)

CPS = read.csv("CPSData.csv")
str(CPS)
table(CPS$Industry)
sort(table(CPS$Region))
sort(table(CPS$State))
which.min(CPO$State)
which.min(CPS$State)
minState = sort(table(CPS$State))
which.min(minState$State)
table(CPS$Citizenship)
table(CPS$Citizenship, mean)
mean(CPS$Citizenship)
summary(CPS$Citizenship)
# (116639 + 7073) / (116639 + 7073 + 7590)
table(CPS¤Hispanic)
table(CPS$Hispanic)
table(CPS$Race)
tapply(CPS$Hispanic, CPSRace > 250)
Hispanic = subset(CPS, Hispanic == 1)
nrow(Hispanic)
summary(Hispanic)
summary(CPS)
is.na(CPS$Married)
CPS$Region, is.na(CPS$Married))
summary(CPS)
CPS$Region, is.na(CPS$Married))
table(CPS$Region, is.na(CPS$Married))
table(CPS$Age, is.na(CPS$Married))
table(CPS$Sex, is.na(CPS$Married))
table(CPS$Citizenship, is.na(CPS$Married))
table(CPS$State, is.na(CPS$MetroAreaCode))
summary(State)
summary(CPS$State)
summary(CPS)
table(CPS$Region, is.na(CPS$MetroAreaCode))
tapply(CPS$Region, is.na(CPS$MetroAreaCode), mean)
tapply(CPS$Region, is.na(CPS$MetroAreaCode), mean)
tapply(CPS$State, is.na(CPS$MetroAreaCode), mean)
tapply(is.na(CPS$MetroAreaCode), CPS$State, mean)

sort(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean))
summary(CPS)
MetroArea = read.csv("MetroAreaCodes.csv")
Country = read.csv("CountryCodes.csv")
str(MetroArea)
str(Country)
CPS = merge(CPS, MetroAreaMap, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
str(CPS)
CPS = merge(CPS, MetroArea, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
summary(CPS)
table(CPS$State, is.na(CPS$MetroArea))
str(CPS$MetroArea)
summary(CPS$MetroArea)
sort(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean))
sort(tapply(is.na(CPS$Hispanic), CPS$MetroArea, mean))
sort(tapply(CPS$Hispanic, CPS$MetroArea, mean))
sort(tapply(CPS$Race == "Asian", CPS$MetroArea, mean))
sort(tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean, na.rm=TRUE))

CPS = merge(CPS, Country, by.x="CountryOfBirthCode", by.y="Code", all.x=TRUE)
str(CPS)
summary(CPS)
summary(CPS$Country)

sort(tapply(CPS$Country, CPS$MetroArea, mean, na.rm=TRUE))
sort(tapply(CPS$Country == "United States", CPS$MetroArea, mean))
sort(tapply(CPS$Country == "United States", CPS$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA", mean))
sort(tapply(CPS$Country == "United States", CPS$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA", mean))
sort(tapply(CPS$Country != "United States", CPS$MetroArea, mean))
CPS$MetroArea[New York-Northern New Jersey-Long Island, NY-NJ-PA]
sort(tapply(CPS$Country == "India", CPS$MetroArea, mean, na.rm=TRUE))
sort(tapply(CPS$Country == "Brazil", CPS$MetroArea, mean, na.rm=TRUE))
sort(tapply(CPS$Country == "Somalia", CPS$MetroArea, mean, na.rm=TRUE))

NY = subset(CPS, MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA") 
str(NY)
summary(NY$Country)
table(NY¤Country)
table(NY$Country)
str(NY)
tapply(WHO$Lite, WHO$Region, min, na.rm=TRUE)
summary(CPS)
str(CPS)

sort(tapply(CPS$Country == "Somalia", CPS$MetroArea == "35620", mean, na.rm=TRUE))
sort(tapply(CPS$Country != "United States", CPS$MetroArea == "35620", mean))
sort(tapply(CPS$Country != "United States", CPS$MetroAreaCode == "35620", mean))
sort(tapply(CPS$Country != "United States", CPS$MetroAreaCode == "35620"))
sort(tapply(CPS$Country != "United States", CPS$MetroAreaCode == "35620", mean))
str(NY)
str(CPS)
str(NY)

sort(tapply(CPS$Country != "United States", CPS$MetroAreaCode == "35620", mean))
sort(tapply(CPS$Country != "United States", CPS$MetroAreaCode == "35620", mean, na.rm=TRUE))
CPS$MetroAreaCode[35260]
mean(NY$Country)
sort(tapply(CPS$MetroAreaCode == "35620", CPS¤Country ! = "35260", mean, na.rm=TRUE))
sort(tapply(CPS$MetroAreaCode == "35620", CPS$Country != "35260", mean, na.rm=TRUE))
sort(tapply(CPS$MetroAreaCode == "35620", CPS$Country != "United States", mean, na.rm=TRUE))
nrow(NY)
summary(NY$Country)
# 3731 / 5704
# 1 - 0.06541024
# 1 - 0.6541024

NY = subset(CPS, MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA") 
sort(tapply(CPS$Country != "United States", CPS$MetroArea, mean))
sort(tapply(CPS$Country = "United States", CPS$MetroArea, mean))
sort(tapply(CPS$Country ="United States", CPS$MetroArea, mean))
sort(tapply(CPS$Country =="United States", CPS$MetroArea, mean))
sort(tapply(CPS$Country != "United States", CPS$MetroArea, mean))
solution = subset(tapply(CPS$Country != "United States", CPS$MetroArea, mean))
# 5409 - 3736 - 5 
# 5409 - 3736
# 1668 / 5404
q()

mvt = read.csv("mvtWeek1.csv")
summary(mvt)
str(mvt)

DateConvert = as.Date(strptime(mvt$Date, "%m/%d/%y %H:%M"))
str(mvt)
summary(mvt)

median(mvt$Date)
mvt$Month = months(DateConvert)
mvt$Weekday = weekdays(DateConvert)

str(mvt)
summary(mvt)

table(mvt$Month)
table(mvt$Weekday)
table(mvt$Arrest)
tapply(mvt$Month, mvt$Arrest, mean)
names(mvt)
tapply(mvt$Month, mvt$Arrest == "TRUE", mean)
tapply(mvt$Month, mvt$Arrest == "TRUE", summary)

ArrestCount = as.numeric(mvt$Arrest == "TRUE", na.rm=TRUE))
ArrestCount = as.numeric(mvt$Arrest == "TRUE", na.rm=TRUE)

str(ArrestCount)
mvt$ArrestCount = as.numeric(mvt$Arrest == "TRUE", na.rm=TRUE)
tapply(mvt$ArrestCount, mvt$Month, mean)
tapply(mvt$Month, mvt$ArrestCount, mean)
table(mvt$Arrest,mvt$Month)
table(mvt$Arrest,mvt$Month, mean)